export const products = [
    {
        'id': 1,
        'url': require('./img/img.jpg'),
        'name': 'Adidas Yeezy Boost 350 v2 bred',
        'size': '43 ⅓',
        'price': 370,
        'quantity': 1,
        'inCart': false,
    },
    {
        'id': 2,
        'url': require('./img/img1.jpg'),
        'name': 'Jordan 4 Retro Shimmer (w)',
        'price': 270,
        'size': '40,5',
        'quantity': 1,
        'inCart': false,
    },
    {
        'id': 3,
        'url': require('./img/img2.jpg'),
        'name': 'Nike Dunk High Black White',
        'price': 170,
        'size': '43',
        'quantity': 1,
        'inCart': false,
    },
    {
        'id': 4,
        'url': require('./img/img3.jpg'),
        'name': 'Nike Dunk Low Michigan State',
        'price': 160,
        'size': '42,5',
        'quantity': 1,
        'inCart': false,
    },
    {
        'id': 5,
        'url': require('./img/img4.jpg'),
        'name': 'Jordan 1 Mid light smoke grey (w)',
        'price': 230,
        'size': '40',
        'quantity': 1,
        'inCart': false,
    },
    {
        'id': 6,
        'url': require('./img/flaxslide.png'),
        'name': 'Yeezy Slide Flax',
        'price': 350,
        'size': '48,5',
        'quantity': 1,
        'inCart': false,
    }

]